import { Addition } from 'src/app/Models/Addition';

export const ADDITION_MULTIPLE: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: false,
  isBread: false,
  extraAddition: true,
  IsTop: false,
  haveException: false,
};
export const BUSINESS_ADDITION_MAIN: Partial<Addition> = {
  IsMeal: true,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: false,
  isBread: false,
  extraAddition: false,
  IsTop: false,
  haveException: false,
};
export const BUSINESS_FIRST_MEAL: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: true,
  isBread: false,
  extraAddition: true,
  IsTop: false,
  haveException: false,
};
export const FAVORITES_MULTIPLE: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: true,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: false,
  isBread: false,
  extraAddition: false,
  IsTop: false,
  haveException: false,
};
export const BUSINESS_LAST_MEAL: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: false,
  isBread: false,
  extraAddition: false,
  IsTop: false,
  haveException: false,
};
export const SAUCE_MULTIPLE: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: true,
  isLastMeal: false,
  isBread: false,
  extraAddition: false,
  IsTop: false,
  haveException: false,
};
export const ONE_RADIO: Partial<Addition> = {
  IsMeal: false,
  IsFirstMeal: false,
  NumberOfChoices: 0,
  IsFavorite: false,
  IsAvaliable: true,
  Checked: false,
  IsSauce: false,
  isLastMeal: false,
  isBread: false,
  extraAddition: false,
  IsTop: false,
  haveException: false,
};